name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  builddocker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test stuff
      run: |
        echo "GITHUB_REF = ${{ github.ref }}"
