name: Build

on:
  create:

jobs:
  builddocker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test stuff
      run: |
        echo "GITHUB_REF = ${{ env.GITHUB_REF }}"
