name: BRANCH CI

on:
  push:
    branches:
      - jobify

jobs:
  test_and_bump:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Git Checkout
        id: git_checkout
        uses: actions/checkout@v2

      - name: Setup Python
        id: setup_python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Install Test Dependencies
        id: setup_test_dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml cwltest cwlref-runner

      - name: Calculate Next Autotagging Version
        id: calc_version
        uses: mathieudutour/github-tag-action@v4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true # this calculates the next version without actually tagging
          release_branches: jobify

      - name: Set Env Vars
        id: set_version_env_vars
        run: |
          new_version=${{ steps.calc_version.outputs.new_version }}
          new_tag=${{ steps.calc_version.outputs.new_tag }}
          echo "::set-env name=NEW_VERSION::$new_version"
          echo "::set-env name=NEW_GIT_TAG::$new_tag"

      - name: Build Docker Image For testing
        id: docker_build
        uses: docker/build-push-action@v1
        with:
          repository: tessthyer/${{ github.event.repository.name }}
          # TODO: see about using service account
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          push: false # don't push before testing
          tags: ${{ env.NEW_VERSION }}

      - name: Edit CWL file tool version
        id: edit_cwl
        run: |
          tool_path='echo.cwl'
          new_version=${{ env.NEW_VERSION }}
          python bump_cwl_version.py $tool_path $new_version

      - name: Test CWL
        id: test_cwl
        run: |
          cwltest --test test-descriptions.yaml --tool cwl-runner

      - name: Commit CWL Change
        id: commit_cwl
        uses: stefanzweifel/git-auto-commit-action@v4.2.0
        with:
          commit_message: "Update docker image version in CWL tool to ${{ env.NEW_VERSION }}"

      - name: Git Checkout Again
        id: git_checkout_after_push
        uses: actions/checkout@v2

      - name: Git Tag
        id: git_tag
        uses: mathieudutour/github-tag-action@v4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: false
          release_branches: jobify
          create_annotated_tag: false

      - name: Publish Docker Image
        id: docker_publish
        uses: docker/build-push-action@v1
        with:
          repository: tessthyer/${{ github.event.repository.name }}
          # TODO: see about using service account
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ env.NEW_VERSION }},latest
