name: CI

on:
  push:
    branches:
      - tagging2
    tags:
      - 'v*'

jobs:
  tag_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        id: git_checkout
        uses: actions/checkout@v2
      - name: Git Tag
        id: git_tag
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        uses: mathieudutour/github-tag-action@v4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: false
          release_branches: tagging2
          create_annotated_tag: true
      - name: Set Docker Version
        id: new_docker_version
        run: |
          new_docker_version=${{ steps.git_tag.outputs.new_version }}
          if [[ -z $new_docker_version ]]
          then
            # ref=${{ github.ref }}
            new_docker_version=${GITHUB_REF/refs\/tags\//}
          fi
          echo "::set-env name=NEW_DOCKER_VERSION::$new_docker_version"
      - name: Publish Docker Image
        id: docker_publish
        # uses: elgohr/Publish-Docker-Github-Action@master
        uses: docker/build-push-action@v1
        with:
          # name: tessthyer/${{ github.event.repository.name }}
          repository: tessthyer/${{ github.event.repository.name }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "${{ env.NEW_DOCKER_VERSION }},latest"
