name: CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  tag_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        id: git_checkout
        uses: actions/checkout@v2
      - name: Calculate Next Autotagging Version
        id: calc_version
        # this step runs only if not a tag push
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        uses: mathieudutour/github-tag-action@v4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          release_branches: master
      - name: Set Version
        id: new_version
        run: |
          # get version from tagging step for a branch push
          new_version=${{ steps.calc_version.outputs.new_version }}
          # otherwise get tag version if a tag push
          if [[ -z $new_version ]]
          then
            new_version=${GITHUB_REF/refs\/tags\//}
          fi
          echo "::set-env name=NEW_VERSION::$new_version"
      - name: Build Docker Image For testing
        id: docker_build
        uses: docker/build-push-action@v1
        with:
          repository: tessthyer/${{ github.event.repository.name }}
          # TODO: see about using service account
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          push: false # don't push before testing
          tags: ${{ env.NEW_VERSION }}
      - name: Edit CWL file tool version
        id: edit_cwl
        run: |
          echo "hello, world"
      - name: Test CWL
        id: test_cwl
        run: |
          echo "hello, world? testing, testing"
      - name: Commit CWL
        id: commit_cwl_change
        run: |
          echo "hello world, this is a git commit"
          exit 1
      - name: Git Tag
        id: git_tag
        # this step runs only if not a tag push
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        uses: mathieudutour/github-tag-action@v4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: false
          release_branches: master
          create_annotated_tag: false
      - name: Publish Docker Image
        id: docker_publish
        uses: docker/build-push-action@v1
        with:
          repository: tessthyer/${{ github.event.repository.name }}
          # TODO: see about using service account
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ env.NEW_VERSION }},latest
