name: Tag

on:
  push:
    branches: [ tagging ]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Github Tag
        uses: mathieudutour/github-tag-action@v4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: false
          release_branches: tagging
          create_annotated_tag: true
