name: Tag

on:
  push:
    branches: [ never ]

jobs:
  # tag-on-push:
  #   runs-on: ubuntu-latest
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v1
  #     - name: tag
  #       run: |
  #         set -xe

  #         tag=$(git describe --tags $(git rev-list --tags --max-count=1))
  #         short_sha=$(git rev-parse --short HEAD)
  #         if [[ "$tag" == "$short_sha" || -z "$tag" ]]
  #         then
  #           tag=v0.0.0
  #         fi
  #         patch="${tag##*.}"
  #         new_patch=$((patch+1))
  #         new_tag="${tag%.*}.${new_patch}"
  #         git tag $new_tag
  #         #git push --tags
  #         echo "$new_tag"

  #         set +xe
  #     - name: push
  #       uses: ad-m/github-push-action@master
  #       with:
  #         github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
  #         tags: true
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Github Tag
        uses: mathieudutour/github-tag-action@v4.2
        with:
          # The build action will run after this one because I am using
          # secrets.GH_PERSONAL_ACCESS_TOKEN rather than secrets.GITHUB_TOKEN.
          # If you use the latter, it will not trigger other actions. See for
          # example https://github.community/t5/GitHub-Actions/Push-from-action-even-with-PAT-does-not-trigger-action/m-p/46293#M6505
          # and 
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          dry_run: false
          release_branches: tagging
          create_annotated_tag: true
