name: Tag

on:
  push:
    branches: [ tagging ]

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: tag
        run: |
          set -xe

          echo "tag my own"
          tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          short_sha=$(git rev-parse --short HEAD)
          if [[ "$tag" == "$short_sha" || -z "$tag" ]]
          then
            tag=v0.0.0
          fi
          patch="${tag##*.}"
          new_patch=$((patch+1))
          new_tag="${tag%.*}.${new_patch}"
          git tag $new_tag

          set +xe
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
      # - id: release
      #   uses: rymndhng/release-on-push-action@v0.14.0
      #   with:
      #     bump_version_scheme: patch
      #     prerelease: false
      # - name: Check Output Parameters
      #   run: echo "Got version ${{ steps.release.outputs.tag_name }}"

  # tag:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Github Tag
  #       uses: mathieudutour/github-tag-action@v4.2
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         dry_run: false
  #         release_branches: tagging
  #         create_annotated_tag: true
