name: Tag

on:
  push:
    branches: [ tagging ]

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@v0.14.0
        with:
          bump_version_scheme: patch
          prerelease: false
          
      - name: Check Output Parameters
        run: echo "Got version ${{ steps.release.outputs.tag_name }}"

  # tag:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Github Tag
  #       uses: mathieudutour/github-tag-action@v4.2
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         dry_run: false
  #         release_branches: tagging
  #         create_annotated_tag: true
